---
title: "SARGE Real-Time Data Dashboard"
title-block-banner: true
server: shiny
---

```{r, message=FALSE, warning=FALSE}
#| context: setup

# TO DO
# Documentation
# Some variables are not numeric


#Load packages
library(shiny)
library(shinythemes)
library(tidyverse)
library(lubridate)
library(data.table)
library(DT)
library(ggpubr)
library(cowplot)
library(plotly)

## Load data ##
#Note this code could be adapted for use with the RAD8 (Durridge) and LI7820 N2O Analyzer

## Specifications ##

TIMEZONE = "EST" #Used across all

## EXO DATA ##

#Read in current water quality sonde (EXO2) data from SARGE
exo <- read.table("Example_Data/WILSON_ExoTable.dat", header=TRUE, skip=3, sep= ",")

#Set exo column names
colnames(exo) <- c("TIMESTAMP","RECORD","Date","Time","Chlorophyll_RFU","Chlorophyll_ugL",
              "Conductivity","FDOM_QSU","FDOM_RFU","NLF_conductivity",
              "ODO_sat","ODO_local", "ODO_MgL", "Pressure_psia", "Salinity_PPT", 
              "Specific_Conductivity_uScm", "BGA_PE_RFU", "BGA_PE_ugL",
              "TDS_mg_L","Turbidity_FNU","Wiper_Position_mv","pH","pH_mv","Temp_C", 
              "Depth_m","Battery_v","Cable_v","Wiper_Current_ma","sn","snn")
numeric_columns <- c("RECORD","Chlorophyll_RFU","Chlorophyll_ugL",
              "Conductivity","FDOM_QSU","FDOM_RFU","NLF_conductivity",
              "ODO_sat","ODO_local", "ODO_MgL", "Pressure_psia", "Salinity_PPT", 
              "Specific_Conductivity_uScm", "BGA_PE_RFU", "BGA_PE_ugL",
              "TDS_mg_L","Turbidity_FNU","Wiper_Position_mv","pH","pH_mv","Temp_C", 
              "Depth_m","Battery_v","Cable_v","Wiper_Current_ma")

#Add timezone
exo$TIMESTAMP <- ymd_hms(exo$TIMESTAMP, tz = TIMEZONE)

#Ensure that columns that should be numbers are numeric for plotting:
exo <- exo %>%
  mutate(across(all_of(numeric_columns), as.numeric))

## SONTEK DATA ##

#read in hydrologic data from Sontek IQ (Xylem Analytics)
sontek <- read.table("Example_Data/WILSON_SontekTable.dat", header=TRUE, skip=1, sep= ",")
sontek <- sontek[-(1:3), ]
sontek <- as_tibble(sontek)

#Add timezone
sontek$TIMESTAMP <- ymd_hms(sontek$TIMESTAMP, tz = TIMEZONE)

#Ensure that columns that should be numbers are numeric for plotting:
sontek$Flowrate <- as.numeric(sontek$Flowrate)
sontek$Water_depth <- as.numeric(sontek$Water_depth)
sontek$Index_velocity <- as.numeric(sontek$Index_velocity)

## FLUX DATA ##

#read in gas concentration data from the LI7810 (LI-COR)
flux <- read.table("Example_Data/WILSON_FLUX_7810.dat", header=TRUE, skip=1, sep= ",")
flux <- flux[-(1:2), ]

#Add timezone
flux$TIMESTAMP <- ymd_hms(flux$TIMESTAMP, tz = TIMEZONE)

#Ensure that columns that should be numbers are numeric for plotting:
flux$CH4d_ppm <- as.numeric(flux$CH4)
flux$CO2d_ppm <- as.numeric(flux$CO2)

## RADON DATA ##

#read in radon concentration data from the RAD7 (Durridge)
radon <- read.table("Example_Data/WILSON_Rad7Table.dat", header=TRUE, skip=1, sep= ",")
radon <- radon[-(1:2), ]

#Add timezone
radon$TIMESTAMP <- ymd_hms(radon$TIMESTAMP, tz = TIMEZONE)

#Ensure that columns that should be numbers are numeric for plotting:
radon$Radon_concentration_Rad7 <- as.numeric(radon$Radon_concentration_Rad7)
radon$RH_sample_Rad7 <- as.numeric(radon$RH_sample_Rad7)

## FOR TESTING
input <- list()
input$start_date <- as.POSIXct('2024-09-19 00:00:00', format = "%Y-%m-%d %H:%M:%S")
input$end_date <- as.POSIXct('2024-09-28 00:00:00', format = "%Y-%m-%d %H:%M:%S")
input$exo_vars <- c("Depth_m")
input$rad_vars <- c("Radon_concentration_Rad7", "RH_sample_Rad7")

#Set min and max for date input
min_date <- min(c(exo$TIMESTAMP,
                  sontek$TIMESTAMP,
                  flux$TIMESTAMP,
                  radon$TIMESTAMP), 
                na.rm = T)

max_date <- max(c(exo$TIMESTAMP,
                  sontek$TIMESTAMP,
                  flux$TIMESTAMP,
                  radon$TIMESTAMP), 
                na.rm = T)
```

```{r}
#| panel: input
#| layout-ncol: 2

dateInput('start_date', 'Start date', 
          min = min_date, 
          max = max_date,
          value = "2024-09-19")

dateInput('end_date', 'End date', 
          min = min_date, 
          max = max_date,
          value = "2024-09-27")
```

::: {.row}

::: {.panel-tabset}

## Overview

```{r}
#| panel: fill

h3("Latest data")
htmlOutput("data_latest")
```

## Exo

```{r}
#| panel: fill

plotlyOutput('plot_exo', height = "400px")
```

```{r}
#| panel: sidebar

checkboxGroupInput("exo_vars","Exo variables to plot",
                   choices = colnames(exo)[!colnames(exo) %in% c("TIMESTAMP", "RECORD", "Date", "Time","sn","snn")],
                   selected = c("Depth_m", "Salinity_PPT"))

```

```{r}
#| panel: fill

h3("Table of all exo data")
div(DT::dataTableOutput("table_exo"), style = "font-size:80%")
```

## Sontek

```{r}
#| panel: fill

plotlyOutput('plot_sontek', height = "360px")
```

```{r}
#| panel: sidebar

checkboxGroupInput("sontek_vars","Sontek variables to plot",
                   choices = colnames(sontek)[!colnames(sontek) %in% c("TIMESTAMP", "RECORD", "SONTEK_ID", "Sample_number","yyyy","MM", "dd", "hh", "Minute", "ss")],
                   selected = c("Flowrate", "Index_velocity", "Water_depth"))

```

```{r}
#| panel: fill

h3("Table of all sontek data")
div(DT::dataTableOutput("table_sontek"), style = "font-size:80%")
```

## Flux

```{r}
#| panel: fill

plotlyOutput('plot_flux', height = "360px")
```

```{r}
#| panel: sidebar

checkboxGroupInput("flux_vars","Flux variables to plot",
                   choices = colnames(flux)[!colnames(flux) %in% c("TIMESTAMP", "RECORD", "TimeLong7810", "LI7810_time","Seconds","Nanoseconds")],
                   selected = c("CH4d_ppm", "CO2d_ppm"))
```

```{r}
#| panel: fill

h3("Table of all flux data")
div(DT::dataTableOutput("table_flux"), style = "font-size:80%")
```

## Radon

```{r}
#| panel: fill

plotlyOutput('plot_radon', height = "360px")
```

```{r}
#| panel: sidebar

checkboxGroupInput("rad_vars","Rad7 variables to plot",
                   choices = colnames(radon)[!colnames(radon) %in% c("TIMESTAMP", "RECORD", "RECORD_RAD7", "Year_RAD7","Month_RAD7","Day_Rad7", "Hour_Rad7", "Minute_Rad7")],
                   selected = c("Radon_concentration_Rad7", "RH_sample_Rad7"))

```

```{r}
#| panel: fill

h3("Table of all radon data")
div(DT::dataTableOutput("table_radon"), style = "font-size:80%")
```

:::

:::

```{r}
#| context: server

#Code for plots
output$plot_exo <- renderPlotly({
  exo_recent <- exo %>%
    filter(as.Date(TIMESTAMP) >= input$start_date,
           as.Date(TIMESTAMP) <= input$end_date) %>%
    select(TIMESTAMP, all_of(input$exo_vars)) %>%
    pivot_longer(input$exo_vars) 
  
  p1 <- exo_recent %>%
    ggplot(aes(x=TIMESTAMP, y=value)) + 
    geom_point(size = 0.3)+
    theme_classic()+
    facet_wrap(~name, scales = "free_y")+
    theme(axis.title.x = element_blank())
  
  plotly::ggplotly(p1, tooltip=c("TIMESTAMP", "value"))
})

output$plot_sontek <- renderPlotly({
  sontek_recent <- sontek %>%
    filter(as.Date(TIMESTAMP) >= input$start_date,
           as.Date(TIMESTAMP) <= input$end_date) %>%
    select(TIMESTAMP, all_of(input$sontek_vars)) %>%
    pivot_longer(input$sontek_vars) 
  
  p1 <- sontek_recent %>%
    ggplot(aes(x=TIMESTAMP, y=value)) + 
    geom_point(size = 0.3)+
    theme_classic()+
    facet_wrap(~name, scales = "free_y")+
    theme(axis.title.x = element_blank())
  
  plotly::ggplotly(p1, tooltip=c("TIMESTAMP", "value"))
})

output$plot_flux <- renderPlotly({
  flux_recent <- flux %>%
    filter(as.Date(TIMESTAMP) >= input$start_date,
           as.Date(TIMESTAMP) <= input$end_date) %>%
    select(TIMESTAMP, all_of(input$flux_vars)) %>%
    pivot_longer(input$flux_vars) 
  
  p1 <- flux_recent %>%
    ggplot(aes(x=TIMESTAMP, y=value)) + 
    geom_point(size = 0.3)+
    theme_classic()+
    facet_wrap(~name, scales = "free_y")+
    theme(axis.title.x = element_blank())
  
  plotly::ggplotly(p1, tooltip=c("TIMESTAMP", "value"))
})

output$plot_radon <- renderPlotly({
  rad_recent <- radon %>%
    filter(as.Date(TIMESTAMP) >= input$start_date,
           as.Date(TIMESTAMP) <= input$end_date) %>%
    select(TIMESTAMP, all_of(input$rad_vars)) %>%
    pivot_longer(input$rad_vars) 
  
  p1 <- rad_recent %>%
    ggplot(aes(x=TIMESTAMP, y=value)) + 
    geom_point(size = 0.3)+
    theme_classic()+
    facet_wrap(~name, scales = "free_y")+
    theme(axis.title.x = element_blank())
  
  plotly::ggplotly(p1, tooltip=c("TIMESTAMP", "value"))
})

#Code for data tables
output$table_exo <- DT::renderDataTable({exo %>%
    arrange(rev(TIMESTAMP))},
    rownames = F,
    class = "display nowrap")
output$table_sontek <- DT::renderDataTable({sontek %>%
    arrange(rev(TIMESTAMP))},
    rownames = F,
    class = "display nowrap")
output$table_radon <- DT::renderDataTable({radon %>%
    arrange(rev(TIMESTAMP))},
    rownames = F,
    class = "display nowrap")
output$table_flux <- DT::renderDataTable({flux %>%
    arrange(rev(TIMESTAMP))},
    rownames = F,
    class = "display nowrap")

#Max timesteps for overview page
output$data_latest <- renderText({
  formatted_date_flux <- paste(format(max(flux$TIMESTAMP, na.rm = T), 
                                 "%Y-%m-%d %H:%M:%S"), 
                          TIMEZONE)
  formatted_date_exo <- paste(format(max(exo$TIMESTAMP, na.rm = T), 
                                 "%Y-%m-%d %H:%M:%S"), 
                          TIMEZONE)
  formatted_date_rad <- paste(format(max(radon$TIMESTAMP, na.rm = T), 
                                 "%Y-%m-%d %H:%M:%S"), 
                          TIMEZONE)
  formatted_date_sontek <- paste(format(max(sontek$TIMESTAMP, na.rm = T), 
                                 "%Y-%m-%d %H:%M:%S"), 
                          TIMEZONE)
  formatted_list <- paste(
    "<ul><li><b>Exo:</b> ", formatted_date_exo, "</li>
    <li><b>Sontek:</b> ", formatted_date_sontek, "</li>
    <li><b>Flux:</b> ", formatted_date_flux, "</li>
    <li><b>Radon:</b> ", formatted_date_rad, "</li></ul>")
  
  return(formatted_list)
  })

```